language: python
python:
  - "3.5"
before_install:
  - sudo apt-get update -qq
install:
  - sudo apt-get install realpath
  - sudo apt-get install cmake make gcc
  - sudo apt-get install -qq fuse fuse-utils libfuse-dev
  - sudo apt-get install -qq user-mode-linux
  - cmake .
  - make
script: ./umltest.sh
