language: c
install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq fuse fuse-utils libfuse-dev python3 user-mode-linux
  - sudo mknod /dev/fuse c 10 229
  - sudo chmod 666 /dev/fuse
  - cmake .
  - make
script: ./umltest.sh
